sudo: required
services:
  - docker

language: python
python:
- 3.6

install:
  - pip install pyyaml

script:
  - NOTEBOOK_IMAGE=$(python -c "import yaml; f = open('jupyter-config.yml'); spec = yaml.load(f.read()); print('{}:{}'.format(spec['jupyterhub']['singleuser']['image']['name'], spec['jupyterhub']['singleuser']['image']['tag']));")
  - docker pull $NOTEBOOK_IMAGE
  - docker run -d --name notebook -t $NOTEBOOK_IMAGE
  - docker cp notebook:/pre-home/worker-template.yml worker-template.yml
  - WORKER_IMAGE=$(python -c "import yaml; f = open('worker-template.yml'); spec = yaml.load(f.read()); print(spec['spec']['containers'][0]['image']);")
  - docker stop notebook
  - docker pull $WORKER_IMAGE
  - # start scheduler in notebook server
  - docker run -p 8888:8888 -p 8786:8786 -p 8787:8787 -d $NOTEBOOK_IMAGE start.sh /opt/conda/bin/dask-scheduler --port 8786 --bokeh-port 8787 &
  - # start worker
  - docker run --net="host" -d $WORKER_IMAGE /opt/conda/bin/dask-worker localhost:8786 --worker-port 8666 --nanny-port 8785 &
  - # notebook server for user connection
  - docker create --name tester --net="host" $NOTEBOOK_IMAGE
  - # copy test suite to test image
  - docker cp notebook_test.py tester:/usr/bin
  - # run test suite
  - docker start tester
  - docker exec tester python /usr/bin/notebook_test.py

  # - chartpress --commit-range ${TRAVIS_COMMIT_RANGE}

# install:
#   - cd docker_images/notebook
#   - docker build -t rhodium/notebook:$TAG .
#   - cd ../worker
#   - docker build -t rhodium/worker:$TAG .

# script:
#   - docker images rhodium/notebook:$TAG
#   - docker images rhodium/worker:$TAG

# #add push
# after_success:
#   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#     docker push rhodium/worker:$TAG;
#     docker push rhodium/worker-tc:$TAG;
#     docker push rhodium/notebook:$TAG;
#     fi

git: 
  depth: false

deploy:
  - provider: script
    skip_cleanup: true
    # script: bash deploy.sh
    env:
      - LOAD_BALANCER_IP=35.230.96.6

    on:
      branch: dev

  - provider: script
    skip_cleanup: true
    # script: bash deploy.sh
    env:
      - LOAD_BALANCER_IP=35.203.134.147
    on:
      branch: master
