
sudo: required
language: python
dist: bionic

services:
- docker

python:
- 3.6

git:
  depth: false

env:
  global:
  - PATH=$HOME/google-cloud-sdk/bin:$PATH
  - PROJECT_ID="rhg-project-1"
  - ZONE="us-west1-a"

install:
- pip install pyyaml
- sudo apt-get update && sudo apt-get install -y apt-transport-https
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
- sudo touch /etc/apt/sources.list.d/kubernetes.list
- echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update
- sudo apt-get install -y kubectl
-
- curl -Lo /tmp/helm-linux-amd64.tar.gz https://kubernetes-helm.storage.googleapis.com/helm-v2.8.2-linux-amd64.tar.gz
- tar -xvf /tmp/helm-linux-amd64.tar.gz -C /tmp/
- chmod +x  /tmp/linux-amd64/helm && sudo mv /tmp/linux-amd64/helm /usr/local/bin/
- bash gcloud-sdk-configure.sh

script:
- bash test_pairing.sh

# deploy:
# - provider: script
#   skip_cleanup: true
#   script: bash deploy-test.sh
#   on:
#     branch: dev

# - provider: script
#   skip_cleanup: true
#   script: bash deploy-prod.sh
#   on:
#     branch: master
