sudo: required

services:
  - docker
env: 
  - TAG=2018-07-10

# install:
# - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
# - pip install --default-timeout=100 git+https://github.com/jupyterhub/chartpress.git
# script:
# - chartpress --commit-range ${TRAVIS_COMMIT_RANGE}

install:
  - cd docker_images/notebook
  - docker build -t rhodium/notebook:$TAG .
  - cd ../worker
  - docker build -t rhodium/worker:$TAG .

script:
  - docker images rhodium/notebook:$TAG
  - docker images rhodium/worker:$TAG

#add push
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rhodium/worker:$TAG;
    docker push rhodium/worker-tc:$TAG;
    docker push rhodium/notebook:$TAG;
    fi

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch:
      - master
