sudo: required
services:
  - docker

language: python
python:
- 3.6

install:
  - pip install pyyaml

script:
  - bash test_pairing.sh

  # - chartpress --commit-range ${TRAVIS_COMMIT_RANGE}

# install:
#   - cd docker_images/notebook
#   - docker build -t rhodium/notebook:$TAG .
#   - cd ../worker
#   - docker build -t rhodium/worker:$TAG .

# script:
#   - docker images rhodium/notebook:$TAG
#   - docker images rhodium/worker:$TAG

# #add push
# after_success:
#   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#     docker push rhodium/worker:$TAG;
#     docker push rhodium/worker-tc:$TAG;
#     docker push rhodium/notebook:$TAG;
#     fi

git: 
  depth: false

deploy:
  - provider: script
    skip_cleanup: true
    # script: bash deploy.sh
    env:
      - LOAD_BALANCER_IP=35.230.96.6

    on:
      branch: dev

  - provider: script
    skip_cleanup: true
    # script: bash deploy.sh
    env:
      - LOAD_BALANCER_IP=35.203.134.147
    on:
      branch: master
