
sudo: required
language: python
dist: bionic

services:
- docker

python:
- 3.6

git:
  depth: false

env:
  global:
  - PATH=$HOME/google-cloud-sdk/bin:$PATH
  - PROJECT_ID="rhg-project-1"
  - ZONE="us-west1-a"

install:
- pip install pyyaml

script:
- bash test_pairing.sh

# deploy:
# - provider: script
#   skip_cleanup: true
#   script: bash deploy-test.sh
#   on:
#     branch: dev

# - provider: script
#   skip_cleanup: true
#   script: bash deploy-prod.sh
#   on:
#     branch: master
