jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: v0.3.0-alpha.1
    storage:
      capacity: 10Gi
      dynamic:
        # storageClass: ssd
        storageClass: standard
    cpu:
      limit: 3.75
      guarantee: 3.75
    memory:
      limit: 24G
      guarantee: 24G
  hub:
    db:
      upgrade: true
    pdb:
      enabled: false
      minAvailable: 0
    extraConfig:
      customPodHook: |
            # runs container in privileged mode for FUSE mount access
            from kubernetes import client
            def modify_pod_hook(spawner, pod):
                pod.spec.containers[0].security_context = client.V1SecurityContext(
                    privileged=True,
                    capabilities=client.V1Capabilities(
                        add=['SYS_ADMIN']
                    )
                )
                return pod
            c.KubeSpawner.modify_pod_hook = modify_pod_hook
            c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
            c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
# The templates section is borrowed from the pangeo approach, i.e.
# https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/config/common.yaml
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"

  scheduling:
    userScheduler:
      enabled: true
    userPlaceholder:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    corePods:
      nodeAffinity:
        matchNodePurpose: require
  cull:
    timeout: 259200

  proxy:
    secretToken: OVERRIDEME
    https:
      letsencrypt:
        contactEmail: mdelgado@rhg.com

  auth:
    type: github
    scopes:
      - "read:user"
    orgWhitelist:
      - RhodiumGroup
    admin:
      access: true
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
        - mattgoldklang
    whitelist:
      users:
        - bolliger32
        - dpa9694
        - mayaanorman
