jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: c189c49077ca5ffe36c9e538b7fcd89f39eedc66
    storage:
      capacity: 10Gi
      dynamic:
        storageClass: pd-ssd
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 12G
      guarantee: 4G
  hub:
    db:
      upgrade: true
    pdb:
      enabled: false
      minAvailable: 0
    extraConfig:
      customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook
        c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
# The templates section is borrowed from the pangeo approach, i.e.
# https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/config/common.yaml
# TODO: Maybe just merge this template into the notebook image repo and do the
# configuration there rather than maintaining a separate repo and mounting it
# in this deploy config?
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"

  scheduling:
    userScheduler:
      enabled: true
    userPlaceholder:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    corePods:
      nodeAffinity:
        matchNodePurpose: require
  cull:
    timeout: 259200

  auth:
    type: github
    github:
      callbackUrl: "https://test2.climate-kube.com/hub/oauth_callback"
    scopes:
      - "read:user"
    admin:
      access: true
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
    whitelist:
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
        - alihamidi1
        - andyhultgren
        - cledna
        - dpa9694
        - ferleejc
        - hanskolus
        - hpitt
        - jaysayre
        - kemccusker
        - mattgoldklang
        - samirasiddique
        - smohan-rhg
        - wjherndon
