jupyterhub:
  singleuser:
    # see https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html for a
    # description of configuration options
    profileList:
      - display_name: "Rhodium:base stable"
        description: "This is the stable build of our <a href=\"https://github.com/RhodiumGroup/docker_images/tree/v0.3.0-alpha.1\">default notebook</a>. Use this if you're not sure."
        kubespawner_override:
          image: rhodium/notebook:v0.3.0-alpha.1
          start_timeout: 900
      - display_name: "Rhodium: base stable (large)"
        description: "Larger notebook allowance, with known stable build of <a href=\"https://github.com/RhodiumGroup/docker_images/tree/v0.3.0-alpha.1\">default notebook</a>"
        kubespawner_override:
          image: rhodium/notebook:v0.3.0-alpha.1
          cpu_limit: 7.5
          mem_limit: 48G
      - display_name: "Rhodium:base latest"
        description: "This is the version of the notebook deployed on <a href=\"https://github.com/RhodiumGroup/docker_images\">docker_images@master</a>. Use this if you want to test out new features!"
        kubespawner_override:
          image: rhodium/notebook:latest
      - display_name: "Rhodium:base latest (large)"
        description: "Larger notebook allowance, with the latest build of <a href=\"https://github.com/RhodiumGroup/docker_images\">docker_images@master</a>"
        kubespawner_override:
          image: rhodium/notebook:latest
          cpu_limit: 7.5
          mem_limit: 48G
          start_timeout: 900
      - display_name: 'Coastal: pyTC stable'
        description: "Known stable build of <a href=\"https://github.com/RhodiumGroup/docker_images/tree/pyTC-v0.1.0\">rhodium/docker_images@dev-pyTC-base branch</a>"
        kubespawner_override:
          image: 'rhodium/notebook:pyTC-v0.1.0'
      - display_name: 'Coastal: pyTC stable (large)'
        description: "Larger notebook allowance, with known stable build of <a href=\"https://github.com/RhodiumGroup/docker_images/tree/pyTC-v0.1.0\">rhodium/docker_images@dev-pyTC-base branch</a>"
        kubespawner_override:
          image: 'rhodium/notebook:pyTC-v0.1.0'
          cpu_limit: 7.5
          mem_limit: 48G
          start_timeout: 900
      - display_name: 'Coastal: pyTC latest'
        description: "Latest build of <a href=\"https://github.com/RhodiumGroup/docker_images/tree/dev-pyTC-base\">rhodium/docker_images@dev-pyTC-base branch</a>"
        kubespawner_override:
          image: 'rhodium/notebook:dev-pyTC-base'
      - display_name: "Coastal: pyTC latest (large)"
        description: "Larger notebook allowance, with the latest build of <a href=\"https://github.com/RhodiumGroup/docker_images/tree/dev-pyTC-base\">rhodium/docker_images@dev-pyTC-base branch</a>"
        kubespawner_override:
          image: 'rhodium/notebook:dev-pyTC-base'
          cpu_limit: 7.5
          mem_limit: 48G
          start_timeout: 900
    # image:
    #   name: rhodium/notebook
    #   tag: v0.3.0-alpha.1
    storage:
      capacity: 10Gi
      dynamic:
        # storageClass: ssd
        storageClass: standard
    cpu:
      limit: 3.75
      guarantee: 3.75
    memory:
      limit: 24G
      guarantee: 24G
    start_timeout: 900
    pullPolicy: Always
  hub:
    db:
      upgrade: true
    pdb:
      enabled: false
      minAvailable: 0
    imagePullPolicy: Always
    extraConfig:
      customPodHook: |
            # runs container in privileged mode for FUSE mount access
            from kubernetes import client
            def modify_pod_hook(spawner, pod):
                pod.spec.containers[0].security_context = client.V1SecurityContext(
                    privileged=True,
                    capabilities=client.V1Capabilities(
                        add=['SYS_ADMIN']
                    )
                )
                return pod
            c.KubeSpawner.modify_pod_hook = modify_pod_hook
            c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
            c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
# The templates section is borrowed from the pangeo approach, i.e.
# https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/config/common.yaml
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"

  scheduling:
    userScheduler:
      enabled: true
    userPlaceholder:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    corePods:
      nodeAffinity:
        matchNodePurpose: require
  cull:
    timeout: 259200

  proxy:
    secretToken: OVERRIDEME
    https:
      letsencrypt:
        contactEmail: mdelgado@rhg.com

  auth:
    type: github
    scopes:
      - "read:user"
    orgWhitelist:
      - RhodiumGroup
    admin:
      access: true
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
        - mattgoldklang
    whitelist:
      users:
        - bolliger32
        - dpa9694
        - mayaanorman
