jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: dev-merge-octave
    storage:
      capacity: 10Gi
  hub:
    db:
      upgrade: true
    pdb:
      enabled: false
      minAvailable: 0
    extraConfig:
      customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook
  scheduling:
    userPlaceholder:
      enabled: false

  cull:
    timeout: 259200
