rbac:
  enabled: true

jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: 2018-07-05.01
    storage:
      capacity: 10Gi
    dynamic:
      storageClass: jupyterhub-user-ssd
    serviceAccountName: daskkubernetes
    cmd: ['start-singleuser.sh']
    defaultUrl: "/lab"
    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true

  hub:
    extraConfig: 
      customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook
        c.Authenticator.whitelist = {"jgerardsimcock", 
                                      "delgadom",
                                      "jiacan", 
                                      "andyhultgren",
                                      "kemccusker"
                                      }


        c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/custom/images/logo.png'
        c.JupyterHub.template_paths = ['/usr/local/share/jupyter/hub/custom_templates/',
                                      '/usr/local/share/jupyter/hub/templates/']

    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/ClimateImpactLab/climate-impactlab-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyter/hub/custom_templates
        name: custom-templates
        subPath: "climate-impactlab-templates/templates"
      - mountPath: /usr/local/share/jupyter/hub/static/custom
        name: custom-templates
        subPath: "climate-impactlab-templates/assets"

    image:
      name: jupyterhub/k8s-hub
      tag: 36188c8  

  proxy: 
    service: 
      loadBalancerIP: 35.233.200.119
  cull:
    enabled: true
    users: false
    timeout: 3600
    every: 600 

  prePuller:
    hook:
      enabled: false