jupyterhub:
  singleuser:
    image:
      name: rhodium/notebook
      tag: 91e8177fe0db3a60b343ff01a5deb699bcb6eb2a
    storage:
      capacity: 10Gi
      dynamic:
        storageClass: ssd
        # storageClass: standard
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 24G
      guarantee: 6G
  hub:
    db:
      upgrade: true
    pdb:
      enabled: false
      minAvailable: 0
    extraConfig:
      customPodHook: |
        c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
# The templates section is borrowed from the pangeo approach, i.e.
# https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/config/common.yaml
# TODO: Maybe just merge this template into the notebook image repo and do the
# configuration there rather than maintaining a separate repo and mounting it
# in this deploy config?
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"

  scheduling:
    userScheduler:
      enabled: true
    userPlaceholder:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    corePods:
      nodeAffinity:
        matchNodePurpose: require
  cull:
    timeout: 259200

  proxy:
    secretToken: OVERRIDEME
    https:
      letsencrypt:
        contactEmail: mdelgado@rhg.com

  auth:
    type: github
    scopes:
      - "read:user"
    orgWhitelist:
      - RhodiumGroup
    admin:
      access: true
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
        - mattgoldklang
    whitelist:
      users:
        - bolliger32
        - dpa9694
        - mayaanorman
