# This config is based off of the approach used by the Pangeo cloud deployments
# (https://github.com/pangeo-data/pangeo-cloud-federation)
jupyterhub:
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  singleuser:
    # see https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html for a
    # description of configuration options
    image:
      pullPolicy: "Always"
      name: gcr.io/rhg-project-1/notebook
      tag: v1.0.0
    startTimeout: 600
    profileList:
      - display_name: "Rhodium base: stable"
        description: "Stable build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@master</a>. (v1.0.0"
        default: true
      - display_name: "Rhodium base: stable (large)"
        description: "Larger notebook allowance, with the stable build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@master</a> (v1.0.0)"
        kubespawner_override:
          cpu_limit: 7.5
          cpu_guarantee: 7.5
          mem_limit: 45G
          mem_guarantee: 45G
      - display_name: "Rhodium base: latest"
        description: "Latest build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@master</a>."
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:latest
      - display_name: "Rhodium base: latest (large)"
        description: "Larger notebook allowance, with the latest build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@master</a>"
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:latest
          cpu_limit: 7.5
          cpu_guarantee: 7.5
          mem_limit: 45G
          mem_guarantee: 45G
      - display_name: "Coastal: stable"
        description: "Stable build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@coastal</a> (v1.0.0)"
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:v1.0.0-coastal
      - display_name: "Coastal: stable (large)"
        description: "Larger notebook allowance, with the stable build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@coastal</a> (v1.0.0)"
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:v1.0.0-coastal
          cpu_limit: 7.5
          cpu_guarantee: 7.5
          mem_limit: 45G
          mem_guarantee: 45G
      - display_name: "Coastal: latest"
        description: "Latest build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@coastal</a>"
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:coastal
      - display_name: "Coastal: latest (large)"
        description: "Larger notebook allowance, with the latest build of <a href=\"https://gitlab.com/rhodium/infra_management/google/jupyterhub-images/docker_images\">docker_images@coastal</a>"
        kubespawner_override:
          image: gcr.io/rhg-project-1/notebook:coastal
          cpu_limit: 7.5
          cpu_guarantee: 7.5
          mem_limit: 45G
          mem_guarantee: 45G
    storage:
      capacity: 10Gi
    cpu:
      limit: 3.75
      guarantee: 3.75
    memory:
      limit: 22.5G
      guarantee: 22.5G
    cloudMetadata:
      blockWithIptables: false
  hub:
    resources:
      requests:
        cpu: "0.25"
        memory: 0.5Gi
      limits:
        cpu: "1.25"
        memory: 1Gi
    extraConfig:
      customPodHook: |
            # runs container in privileged mode for FUSE mount access
            from kubernetes import client
            def modify_pod_hook(spawner, pod):
                pod.spec.containers[0].security_context = client.V1SecurityContext(
                    privileged=True,
                    capabilities=client.V1Capabilities(
                        add=['SYS_ADMIN']
                    )
                )
                return pod
            c.KubeSpawner.modify_pod_hook = modify_pod_hook
            c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
            c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/RhodiumGroup/rhodium-custom-jupyterhub-templates.git"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "rhodium-custom-jupyterhub-templates/assets"
    services:
      dask-gateway:
        apiToken: OVERRIDEME
  scheduling:
    userScheduler:
      enabled: true
    userPlaceholder:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    corePods:
      nodeAffinity:
        matchNodePurpose: require
  cull:
    timeout: 259200

  proxy:
    secretToken: OVERRIDEME
    https:
      enabled: true
      letsencrypt:
        contactEmail: mdelgado@rhg.com

  auth:
    type: github
    scopes:
      - "read:user"
      - "read:org"
    admin:
      access: true
      users:
        - bolliger32
        - brews
        - delgadom
        - dgergel
        - mattgoldklang

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: OVERRIDEME
    extraConfig:
      optionHandler: |
        from dask_gateway_server.options import Options, String, Select, Mapping
        from math import ceil

        def cluster_options(user):

            # A mapping from profile name to configuration overrides
            standard_cores = 1.8
            standard_mem = 12.7
            scaling_factors = {
                "micro": 0.5,
                "standard": 1,
                "big": 2,
                "giant": 4
            }

            default_tolerations = {
                "0": {
                    "key": "k8s.dask.org_dedicated",
                    "operator": "Equal",
                    "value": "worker",
                    "effect": "NoSchedule"
                }
            }

            def option_handler(options):
                if (":" not in options.worker_image) or (":" not in options.scheduler_image):
                    raise ValueError("When specifying an image you must also provide a tag")
                extra_annotations = {
                    "hub.jupyter.org/username": user.name
                }
                default_extra_labels = {
                    "hub.jupyter.org/username": user.name,
                }
                
                this_env = options.env_items

                # add extra pip packages to be picked up by prepare.sh
                if options.extra_pip_packages != "":
                    this_env["EXTRA_PIP_PACKAGES"] = options.extra_pip_packages

                # add gcsfuse Tokens
                this_env["GCSFUSE_TOKENS"] = options.gcsfuse_tokens

                # add google cloud auth
                this_env["GOOGLE_APPLICATION_CREDENTIALS"] = f"/opt/gcsfuse_tokens/{options.cred_name}.json"

                # calculate cpu request and limit
                cpu_req = scaling_factors[options.profile] * standard_cores

                return {
                    "worker_cores": cpu_req,
                    # see https://github.com/dask/dask-gateway/blob/e409f0e87f45e0a51fd7c009b5ec010bc5253bf1/dask-gateway-server/dask_gateway_server/backends/kubernetes/controller.py#L1055
                    "worker_cores_limit": ceil(cpu_req), # this is necessary to get correct nthreads
                    "worker_memory": f"{scaling_factors[options.profile] * standard_mem:.2f}G",
                    # setting images separately here to get a light-weight scheduler
                    "worker_extra_container_config": {
                        "image": options.worker_image,
                        "imagePullPolicy": "Always",
                        "securityContext": {
                          "privileged": True # allows gcsfuse mount
                        }
                    },
                    "scheduler_extra_container_config": {
                        "image": options.scheduler_image,
                        "imagePullPolicy": "Always",
                    },
                    "worker_extra_pod_annotations": extra_annotations,
                    "worker_extra_pod_config": {
                        "tolerations": list(options.worker_tolerations.values())
                    },
                    "worker_extra_pod_labels": {
                        **default_extra_labels,
                        **options.extra_worker_labels,
                    },
                    "scheduler_extra_pod_annotations": extra_annotations,
                    "scheduler_extra_pod_labels": default_extra_labels,
                    "scheduler_extra_pod_config": {
                        "tolerations": list(default_tolerations.values()),
                    },
                    "environment": this_env,
                    "idle_timeout": 3600*6 # 6 hour idle timeout
                }
            return Options(
                Select(
                    "profile",
                    ["micro", "standard", "big", "giant"],
                    default="standard",
                    label="Cluster Profile"
                ),
                String("worker_image", default="rhodium/worker:gateway", label="Worker Image"),
                String("scheduler_image", default="rhodium/scheduler:gateway", label="Scheduler Image"),
                String("extra_pip_packages", default="", label="Extra pip Packages"),
                String("gcsfuse_tokens", default="", label="GCSFUSE Tokens"),
                String("cred_name", default="rhg-data", label="Bucket for Google Cloud Creds"),
                Mapping("worker_tolerations", default=default_tolerations, label="Worker Pod Tolerations"),
                Mapping("extra_worker_labels", default={}, label="Extra Worker Pod Labels"),
                Mapping("env_items", default={}, label="Environment Variables"),
                handler=option_handler,
            )
        c.Backend.cluster_options = cluster_options