jupyterhub:
  proxy:
  # output of second execution of 'openssl rand -hex 32'
    secretToken: "0da01a037cb1606a6ef611692efb0daddf3b7348bde96c79ad106f3f16e2fc2d"
  # output of first execution of 'openssl rand -hex 32'
