apiVersion: v1
name: rhg-hub
version: v0.1.6
description: An extention of jupyterhub-pangeo
maintainers:
  - name: Ian Bolliger (UC Berkeley)
    email: bolliger@berkeley.edu
  - name: Michael Delgado (Rhodium Group)
    email: mdelgado@rhg.com
  - name: Brewster Malevich (Rhodium Group)
    email: bmalevich@rhg.com
